name: QA Automation Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  smoke-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout QA repository
        uses: actions/checkout@v6

      - name: Checkout Medusa application
        uses: actions/checkout@v6
        with:
            repository: Anubhavsikka16/dtc-starter-clean
            path: medusa

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Install Playwright browsers
        run: poetry run playwright install --with-deps chromium

      - name: Run smoke tests
        env:
            BASE_URL: ${{ secrets.BASE_URL }}
            API_BASE_URL: ${{ secrets.API_BASE_URL }}

            ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
            ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

            BROWSER: ${{ secrets.BROWSER }}
            HEADLESS: ${{ secrets.HEADLESS }}
            SLOW_MO: ${{ secrets.SLOW_MO }}
            TIMEOUT: ${{ secrets.TIMEOUT }}

            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        run: poetry run python -m pytest -m smoke -v
